const config = {
	recast:'fc5c83159e9e0bbc4d337a3d5983863f',
 	 appId: 'a0a49f12-f8f2-4ec6-b6e7-4c80ad398aed',
 	 appPassword: 'sbYgWot8FqrNpFqoUJqJmav',
 	 intentData:{
 		 "car-dealer":"Hello! How may I help you?",
 	  	 "buy-car":"Which model do you want to buy dear? ..to know more, please contact us at www.lariachevybuick.com/ContactUsForm or you can call us directly at (877) 598-6568.",
 	  	 "trade-in":"Yes, we do. We will need your car’s certificate of title, the car’s current registration, all your car keys and the owner’s manual. If you still have a loan on the car, you will need to have your account number or a payment stub. And you should clean out your car, paying special attention to areas out of sight but convenient for stashing things: under seats, over the visors, in the glovebox and in every corner of the trunk. Visit  www.lariachevybuick.com/SellUsYourCar for more details.",
 	  	 "bad-credit":"Absolutely, but it’s going to cost you. If you have bad credit, then you need to walk into the process knowing that you have to pay a higher rate than what people who don’t have bad credit are going to pay. Contact you personally for more information.",
 	  	 "defaulter":"You need to make EMI payments regularly. Most of the banks allow you to miss one or two payments. However, beyond that you may be treated as a defaulter.                   You may refinance your vehicle loan or trade-in your car.",
 	  	 "documents":"Proof of income (Copies of your pay stubs from the last month, with a total of what you've been paid year-to-date), Credit and banking history, Proof of residence, Vehicle information and Proof of insurance. After submission of the documents, it takes about 3-7 days for processing the loan and getting it sanctioned",
 	  	 "credit-score":"Fill out the Finance Pre-Qualification Form on our website and our representative will reach out to you shortly. Visit https://gmdealersecureforms.cdk.com/6e0860909ed2100484f620145edeeed9/FinancePreQualForm ",
 	  	 "pre-owned-price":"Visit  www.lariachevybuick.com/VehicleSearchResults?search=used for details.",
 	  	 "new-vehicle-price":"Visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick for details.",
 	  	 "buy-lease":"Please visit https://www.edmunds.com/car-leasing/should-you-lease-or-buy-your-car.html",
 	  	 "below-20k":"Yes we do. For more information visit  www.lariachevybuick.com/VehicleSearchResults?search=new&priceRange_min=0&priceRange_max=20000",
 	  	 "benefits":"We care for our customers. Please visit  www.lariachevybuick.com/OwnerCenter to get more details.",
 	  	 "interest-rate":"2.74% ARP for 60 months on new vehicles and 3.09% ARP for 60 month for preowned ones. For more details contact us on (877) 598-6568",
 	  	 "banking":". There are two types of interest rate offered - fixed and floating. You can choose the bank which offers the one you need.",
 	  	 "loan-tenure":" Typical tenures for car loans range from 1-5 years. You can opt for a lower tenure loan if you can service a higher EMI (equated monthly instalment) or a higher tenure loan if you cannot afford high EMI.",
 	  	 "emi":"You can pay EMIs either through post-dated cheques or request the bank to debit your account every month through ECS (electronic clearing system) option.",
 	  	 "used-car-loans":"Yes, financial institutions offer loans to purchase used or second hand cars. However, interest rates would be slightly higher for such vehicles.",
 	  	 "service-apply":"You can visit our website and fill up the service appointment form.  www.lariachevybuick.com/ServiceApptForm  and get an appointment for your car.",
 	  	 "service":"Visit our website for further details on Service. www.lariachevybuick.com/Service",
 	  	 "parts-offers":"Yes, why don’t you check out our website for the service offers. www.lariachevybuick.com/ServiceAndPartsSpecials",
 	  	 "parts-order-form":"Visit our website and fill up the parts order form www.lariachevybuick.com/PartsOrderForm",
 	  	 "tire":"Visit our website and get tire details  www.lariachevybuick.com/TireFinder ",
 	  	 "accessories":"check out our hours of operations on the website and visit our dealership.  www.lariachevybuick.com/HoursAndDirections ",
 	  	 "body-shop":"for more details about body shop, please visit  www.lariachevybuick.com/Body-Shop ",
 	  	 "warranty":" www.lariachevybuick.com/OwnerCenter ",
 	  	 "safety-features":"For information on your query please visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "interior-exterior":"For these details, visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "trims":"For this information please visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "performance":"For the said details please visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "whats-new":"For these details please feel free to visit  www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "tow":" www.lariachevybuick.com/VehicleSearchResults?search=new&make=Chevrolet&make=Buick ",
 	  	 "loaction-hours":"Hi, to find your nearest dealership, please visit www.lariachevybuick.com/HoursAndDirections. ",
 	  	 "new-loan":"Hi, if you applying for a new car loan, please contact us at www.lariachevybuick.com/ContactUsForm or you can call us directly at (877) 598-6568.",
 	  	 "loan":"Do you want new car loan or used car loan?"
 	 }
}
module.exports = config